### ISSUE TITLE
Add recordVersion support to store IPNS records version data

### ISSUE THREAD

**Issue by 0xc0de4c0ffee** [namesys-eth/ccip2-eth-resolver#6]
Off-chain Resolver record type `../version.json` mapped to `recordVersions(bytes32)` function from latest ENS resolver designs.

> `function recordVersions(bytes32 node) external view returns (uint64);`

`../version.json` format, _version is IPNS record's internal version counter.  
``` 
{
    "data" : "0x<abi.encodePacked(_callback.selector, signer, signature, abi.encode(uint64(_version++)))>",
    "version" : _version,
    "prev" : "</ipfs/ipld/hash of last version || "" for first version>"
    //.. other extradata for record
}
```
This should be internal task/records before final IPNS publish. it'll be handy in future clients to debug and update helper & also historical/archive feature if all old IPFS/IPLD data is still pinned out there somewhere.

I was initially thinking  to dump string version number as text record, * it's helper for records manager so we can use recordsVersion to match Namewrapper/latest resolvers.

**Comment by 0xc0de4c0ffee** [comment]
* `"archive": {"vN" : "Nth version of ipfs/ipld/<hash>... list"}`? 
Clients can skip minor versions as list, 
full history can still be resolved from prev value if IPNS/IPFS minor version data is still pinned somewhere in bigger network.

**Comment by sshmatrix** [comment]
This is already take care of in some sense but not exactly in the way you'd like it:

Upon each record update, a `revision` object is created which contains the timestamp, previous versions's hash and the IPNS public key. It is stored in `revision.json` and required by our client before making an update. But that is different than what you are asking, which is to store the version data in the same file `record.json`

**Comment by sshmatrix** [comment]
We have the `Revision` object stored in `revision.json` and updated at each revision. It contains the 

- timestamp, 
- IPNS pubkey, 
- version number and 
- IPFS hash. 
- 
- Currently, it is stored in a serialised + encoded form of a 174-byte array. I can make another file with `version.json` that stores the same in plaintext JSON format.

**Comment by sshmatrix** [comment]
Done

**Comment by 0xc0de4c0ffee** [comment]
?use IPNS/w3name type and validity format in version.json? 
4n = biginit format Number+"n", replace timestamp with ISO string

```
{ 
data: 0x<.....>, 
_sequence :  4n,  
_validity :  "2024-04-29T13:00:49.555000000Z",  
_prev :  "/ipld/bafyreie2nochynilsdmcyqpxid7d2dzdle4dbptvep65kujtg2uywm7jre", 
_archive:{
    "0n":"/ipfs/....",
    ..., 
    "3n" :"/ipld/...." } 
}
```
use `_` prefix for all extradata?

**Comment by sshmatrix** [comment]
I have used exact `w3name` format for now. I will see if I can add underscores easily 😁

**Comment by sshmatrix** [comment]
Underscores are added by default:

`
{"_name":{"_pubKey":{"_key":{}},"_value":"/ipfs/QmStaCMwDufLQHrezhQwmLZJH99UKfdMqbLfPiAQ3t2xnx","_sequence":"0","_validity":"2024-05-06T02:42:23.744Z"}
`
